[package]
name = "eql_macros"
version = "0.1.0"
description = "Procedural macros for eql_core"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
